### PR TITLE
fix(button): release element focus when disabled

### PR DESCRIPTION
**Pull request by mattpottstj**
Also applies to mdc-icon-button

### CODE REVIEW

**Comment by MaximBalaganskiy** [comment]
Could you please give more background why this is needed?
Currently, if I set `button.disabled = true` the `document.activeElement === document.body`.

**Comment by mattpottstj** [comment]
When a button/icon button is disabled programatically, focus of that button is not lost.
A simple exampe is on the data tables navigation demo, clicking the next button, the pagination button is fine until it comes to the end of the recordset. It is then disabled by the framework but remains in focus. 
image

**Comment by MaximBalaganskiy** [comment]
I cannot reproduce unfortunately, could you please make a gif to demonstrate?
ezgif com-gif-maker

**Comment by MaximBalaganskiy** [comment]
Is this still relevant?

**Pull request closed without merging**
