### PR TITLE
feat(chips): add

### PR DESCRIPTION
**Pull request by arjendeblok**
I implemented a lot of chips components. 

I get an error in the app when I try to see if the chips components work as expected.
`Can't figure out a normalized module name for ./mdc-chip/mdc-chip, please call PLATFORM.moduleName() somewhere to help.`

I do not have any idea where to look to solve it.

### CODE REVIEW

**Comment by MaximBalaganskiy** [comment]
I've fixed some things which were obvious to me. It kind of works in the demo app.

Nevertheless, the components are incomplete - event hooks are missing. 
Please have a look at the default implementation - both `mdc-chip` and `mdc-chip-set` subscribe to lots of events. Our wrappers will have to do the same to support interactivity. Most components can use Aurelia's `.trigger` binding. Just bear in mind that these event constants will need to be converted to lower case since Aurelia is case insensitive.

Another thing which I noticed is that chip template does not match the documentation. Although, when I look at the MDC examples, they don't use the proper html structure as well. Not sure what to do here TBH. May be continue as is and if it does not work then fix it. Supporting the proper chip template may be a bit harder because different parts of the component content will need to go to different template places. To do that we'll most likely need to use `processContent` decorator so that it's transparent to an end user.

And finally, could you please lint your changes? There are some places which don't match the syntax of the project. The best way to do that is to install `eslint` vs code extension.

**Comment by MaximBalaganskiy** [comment]
Oh, one more thing. I'm using `changelog` tool for the release notes. It would be fantastic if your commits and the PR followed [angular standard](https://github.com/aurelia-ui-toolkits/aurelia-mdc-web/blob/master/CONTRIBUTING.md#-submit-a-pull-request)

**Comment by arjendeblok** [comment]
I got it running now. My problem was that chips was not added to the webpack.config file of the App.

> I've fixed some things which were obvious to me. It kind of works in the demo app.

I agree with the changes.

> Nevertheless, the components are incomplete - event hooks are missing.

I will have to do that. But first I wanted the App to be running with the chips. But that is working now so I can proceed on that.

> Another thing which I noticed is that chip template does not match the documentation.

I think that the template looks OK now. Please look at the updated examples page for that.
To make it easier I can use `processContent ` later if some parts are missing, e.g. the primary action.

> And finally, could you please lint your changes?

Of course. But I first want it up and running.

**Comment by arjendeblok** [comment]
I have implemented the event hooks. I got stuck with the handling. I cannot get the handlers for the MdcChipSet component working for the events from the MdcChip, e.g. MDCChip::interaction. If I do a DOM listen it works, but with the Aurelia delegate it does not work. 

Please note that the code is not nearly completed, so please only look at this problem.

**Comment by MaximBalaganskiy** [comment]
Luckily, MDC allows tweaking event names. See my commit

**Comment by arjendeblok** [comment]
I think this can be reviewed now for a first release of chips.

**Comment by MaximBalaganskiy** [comment]
A couple of things which I noticed:

* trailing action component is missing
* filter chip with leading icon does not hide the icon when selected
* it would be great to have code snippets next to examples

**Comment by arjendeblok** [comment]
> trailing action component is missing

What is this supposed to do extra instead of the trailing icon? I cannot find any information where this should be put into the chip.

**Comment by MaximBalaganskiy** [comment]
https://github.com/material-components/material-components-web/blob/master/packages/mdc-chips/trailingaction/README.md

**Comment by arjendeblok** [comment]
I have read that a couple of times. Also looked for an example. 
But I really do not understand when to use a trailing icon with a remove icon or a separate trailing action.

**Comment by MaximBalaganskiy** [comment]
> But I really do not understand when to use a trailing icon with a remove icon or a separate trailing action.

Have a look at Angular examples https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/chips/examples

**Comment by arjendeblok** [comment]
Sorry, I do not see it in the Angular examples either. 
In the examples trailing icons are used, but no separate trailing action.
Can you point it to me where it is used?

**Comment by MaximBalaganskiy** [comment]
I thought it was the second example

**Comment by MaximBalaganskiy** [comment]
Judging by the tests the trailing action is added to the gridcell adjacent to the primary gridcell
https://github.com/material-components/material-components-web/blob/bcc58290a7ac7bbbe191d00be003785017f94d29/packages/mdc-chips/chip/test/component.test.ts#L82

That is how it's used in the second Angular example - "Input chips"
https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/chips/examples

**Comment by arjendeblok** [comment]
> Judging by the tests the trailing action is added to the gridcell adjacent to the primary gridcell
> https://github.com/material-components/material-components-web/blob/bcc58290a7ac7bbbe191d00be003785017f94d29/packages/mdc-chips/chip/test/component.test.ts#L82
> 
> That is how it's used in the second Angular example - "Input chips"
> https://trimox.github.io/angular-mdc-web/#/angular-mdc-web/chips/examples

Not really. The second example is using the trailing **icon** and not a trailing **action** with a button.
I updated the examples with an input chipset with leading icons.

**Comment by MaximBalaganskiy** [comment]
Disregard the Angular example then. The test I posted has the proper structure.
The difference is that trailing action is a proper button and has a ripple effect whilst icon does not.

**Comment by arjendeblok** [comment]
Added trailing action.

**Comment by MaximBalaganskiy** [comment]
I've fixed and added a couple of things. Could you please review?
If you're happy I'll merge tomorrow.

**Comment by arjendeblok** [comment]
On the chip primary action you removed the `role` and `tabindex` attributes and set them to `button` and `0`.
But on a filter chip the role shoule be `checkbox` and not `button`.
And sometimes the tabindex could be set to -1 instead of 0.

For the rest it is OK.

**Comment by MaximBalaganskiy** [comment]
You can still set them, no need to duplicate as bindables

**Comment by MaximBalaganskiy** [comment]
Thanks for the contribution 👍

**Pull request merged**
