### PR TITLE
feat(text-field): add blur-on-enter attribute

### PR DESCRIPTION
**Pull request by swalters**
I missed this attribute from Materialize bridge

### CODE REVIEW

**Comment by MaximBalaganskiy** [comment]
How is this used?

**Comment by swalters** [comment]
We use it on data entry forms where user expects Enter to go to next field like Excel does.  It was part of Materialize Bridge and I used it in my app.

**Comment by MaximBalaganskiy** [comment]
It certainly does not work in the demo if you place two consecutive text fields there - first one just looses focus.

**Comment by swalters** [comment]
I don't know the intent then.  I copied what was in Aurelia Materialize because we had used the attribute on several forms.  Doesn't mean it's right though.  I can easily implement a custom attribute if we can't find a need for this

**Comment by MaximBalaganskiy** [comment]
I'm happy to add it, but it does not seem to work - the focus does not move to the next field.

**Comment by swalters** [comment]
This is the reasoning: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/302

**Comment by swalters** [comment]
I can't see where it was ever documented.  If validation works differently now, it may not be needed.

**Comment by MaximBalaganskiy** [comment]
Please review the suggestion. If you're happy we can merge

**Comment by MaximBalaganskiy** [comment]
BTW, this behaviour is the same with the AMB due to the default 'blur' validation trigger

**Comment by swalters** [comment]
@MaximBalaganskiy Looks good to me

**Pull request merged**
