### PR TITLE
fix(mdc-chip): fix removable attribute

### PR DESCRIPTION
**Pull request by swalters**

### CODE REVIEW

**Comment by MaximBalaganskiy** [comment]
Perhaps, we should replace `removable` with `non-removable` - this will make setting the attribute easier

**Comment by swalters** [comment]
renamed to non-removable instead

**Comment by MaximBalaganskiy** [comment]
why close?

**Comment by swalters** [comment]
Sorry, I saw that you committed the rename so I thought this was no longer needed.

**Comment by swalters** [comment]
should have never closed

**Pull request merged**
